In [2]:
import os
from skimage import io
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
import re

In [3]:
def sorted_alphanumeric(data):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(data, key=alphanum_key)

In [4]:
path = 'C:/Users/DPJSIG04-PRO/Documents/capstone/project/panda/mask_resize/'
filename = os.listdir(path)
srtdfile = sorted_alphanumeric(filename)
masks = []

for file in srtdfile:
    print(file)
    mask = io.imread(path + file)
    mask = np.where(mask>0, 255, mask)
    masks.append(mask)





1.tif
2.tif
3.tif
4.tif
5.tif
6.tif
7.tif
8.tif
9.tif
10.tif
11.tif
12.tif
13.tif
14.tif
15.tif
16.tif
17.tif
18.tif
19.tif
20.tif
21.tif
22.tif
23.tif
24.tif
25.tif
26.tif
27.tif
28.tif
29.tif
30.tif
31.tif
32.tif
33.tif
34.tif
35.tif
36.tif
37.tif
38.tif
39.tif
40.tif
41.tif
42.tif
43.tif
44.tif
45.tif
46.tif
47.tif
48.tif
49.tif
50.tif


In [5]:
print(mask)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
print(np.unique(masks))

[  0 255]


In [7]:
for (i, new) in enumerate(masks):
    im = Image.fromarray(new)
    im.save('{}{}{}'.format('C:/Users/DPJSIG04-PRO/Documents/capstone/project/panda/mask_treshold/',i+1,'.tif'))